spring:
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/db
    username: root
    password: 
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8081
